name: Build Jekyll site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown"))'
          
      - name: Render Rmd files
        run: Rscript render_posts.R
        
      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1