name: Build Jekyll site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown"), repos="https://cloud.r-project.org")'
          
      - name: Create directories
        run: |
          mkdir -p _posts
          mkdir -p _Rmd
          
      - name: List directory contents
        run: ls -la
          
      - name: Render Rmd files
        run: |
          Rscript -e 'print(getwd())'
          Rscript -e 'print(list.files())'
          Rscript render_posts.R
        
      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1